version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - /data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drama
      - POSTGRES_USER=drama_user
      - POSTGRES_PASSWORD=pass
  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    restart: on-failure
    volumes:
      - ./:/usr/src/
    ports:
      - "8000:8000"
    depends_on:
      - db
  dramatiq:
    build:
      context: ./
      dockerfile: ./dramatiq/Dockerfile
    depends_on:
      - redis
      - db
